contexts:
  ws-1:
    host: localhost
    port: 63830
    user: user
    privateKeyFile: C:/workspace/cygwin64/home/foo/.ssh/id_rsa
    gcloud:
      project: gcws-project
      region: europe-west6
      cluster: gcws-cluster
      config: gcws-config
      name: ws-1
    dirs:
      - path: /home/user/.ssh
        permissions: "700"
    files:
      - sourcePath: C:/workspace/cygwin64/home/foo/.ssh/id_ed25519
        path: /home/user/.ssh/id_ed25519
        permissions: "0400"
      - sourcePath: C:/workspace/cygwin64/home/foo/.ssh/id_ed25519.pub
        path: /home/user/.ssh/id_ed25519.pub
        permissions: "0700"
  ws-2:
    host: localhost
    port: 63830
    user: user
    privateKeyFile: C:/workspace/cygwin64/home/foo/.ssh/id_rsa
    gcloud:
      project: gcws-project
      region: europe-west6
      cluster: gcws-cluster
      config: gcws-config
      name: ws-2
currentContext: ws-1
filePatches:
  gcloud-ssh-putty:
    file: testdata/patch/ssh.py
    oldBlock:
      - '    if platforms.OperatingSystem.IsWindows():'
      - '      suite = Suite.PUTTY'
      - '      bin_path = _SdkHelperBin()'
      - '    else:'
      - '      suite = Suite.OPENSSH'
      - '      bin_path = None'
      - '    return Environment(suite, bin_path)'
    newBlock:
      - '    suite = Suite.OPENSSH'
      - '    bin_path = None'
      - '    return Environment(suite, bin_path)'
